services:
  mm-stream:
    build: .
    expose:
      - ${MM_PORT:-3000}
    ports:
      - "${MM_PORT:-3000}:${MM_PORT:-3000}"
    environment:
      - MM_PORT=${MM_PORT:-3000}
      - MM_FOLDER=/media
      - MM_HOST=${MM_HOST:-http://localhost:3000}
    volumes:
      - ${MM_FOLDER:-./media}:/media
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`music.klan.cc`)"
      - "traefik.http.routers.media.entrypoints=websecure"
      - "traefik.http.routers.media.tls.certresolver=mydns"
      - "traefik.http.services.media.loadbalancer.server.port=1507"
    networks:
        - traefik

networks:
  traefik:
    external: true
